/* DO NOT EDIT THIS FILE - it is machine generated */

#if CC_TARGET_PLATFORM == CC_PLATFORM_ANDROID


#include <jni.h>
#include <string>
/* Header for class com_candou_knowledgegame_util_JniManager */
#ifndef __knowledgegame__JAVAHelper__
#define __knowledgegame__JAVAHelper__
void wxHelp_JAVA();
void wxSendHelpByFriend_JAVA();
void wxSendToFriendCircle_JAVA();
void buy_JAVA(int goodId);
void playLocalVideo_JAVA(std::string& filename);
void X_shareToFriends_JAVA();
void X_shareToFriend_JAVA();
//#ifdef __cplusplus
//extern "C" {
//#endif
///*
// * Class:     com_candou_knowledgegame_util_JniManager
// * Method:    wxSendHelpByFriend
// * Signature: ()V
// */
//	
//JNIEXPORT void JNICALL Java_com_candou_knowledgegame_util_JniManager_wxSendHelpByFriend
//  (JNIEnv *, jclass);
//
///*
// * Class:     com_candou_knowledgegame_util_JniManager
// * Method:    wxSendHelpByTimeline
// * Signature: ()V
// */
//JNIEXPORT void JNICALL Java_com_candou_knowledgegame_util_JniManager_wxSendHelpByTimeline
//  (JNIEnv *, jclass);
//
//#ifdef __cplusplus
//}
//#endif
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     com_mz_games_crazyvideo_util_JniManager
	* Method:    shareToFriendsCallback
	* Signature: (Z)V
	*/
	JNIEXPORT void JNICALL Java_com_mz_games_crazyvideo_util_JniManager_shareToFriendsCallback
		(JNIEnv *, jclass, jboolean);

	/*
	* Class:     com_mz_games_crazyvideo_util_JniManager
	* Method:    shareToFriendCallback
	* Signature: (Z)V
	*/
	JNIEXPORT void JNICALL Java_com_mz_games_crazyvideo_util_JniManager_shareToFriendCallback
		(JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif/* defined(__knowledgegame__JAVAHelper__) */

#endif

